package com.veterinaria.backend;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.when;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.math.BigDecimal; import java.time.LocalDateTime;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.test.context.bean.override.mockito.MockitoBean; import org.springframework.http.MediaType; import org.springframework.mock.web.MockMultipartFile; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import org.springframework.test.web.servlet.request.RequestPostProcessor; import org.springframework.transaction.annotation.Transactional;
import com.veterinaria.backend.cita.entity.*; import com.veterinaria.backend.cita.enums.*; import com.veterinaria.backend.cita.repository.*; import com.veterinaria.backend.cliente.entity.Cliente; import com.veterinaria.backend.cliente.enums.TipoDocumento; import com.veterinaria.backend.cliente.repository.ClienteRepository; import com.veterinaria.backend.mascota.entity.Mascota; import com.veterinaria.backend.mascota.enums.EspecieMascota; import com.veterinaria.backend.mascota.repository.MascotaRepository; import com.veterinaria.backend.pago.repository.*; import com.veterinaria.backend.comprobante.repository.ComprobanteRepository; import com.veterinaria.backend.peluqueria.entity.*; import com.veterinaria.backend.peluqueria.repository.*; import com.veterinaria.backend.peluqueria.storage.*; import com.veterinaria.backend.servicio.entity.Servicio; import com.veterinaria.backend.servicio.enums.TipoServicio; import com.veterinaria.backend.servicio.repository.ServicioRepository; import com.veterinaria.backend.support.PostgreSqlContainerConfiguration; import com.veterinaria.backend.usuario.entity.*; import com.veterinaria.backend.usuario.enums.NombreRol; import com.veterinaria.backend.usuario.repository.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") @Transactional
class FlujoPeluqueriaPagoComprobanteIntegrationTest extends PostgreSqlContainerConfiguration {
 @Autowired MockMvc mvc; @Autowired CitaRepository citas; @Autowired CitaServicioRepository citaServicios; @Autowired ClienteRepository clientes; @Autowired MascotaRepository mascotas; @Autowired UsuarioRepository usuarios; @Autowired UsuarioRolRepository usuarioRoles; @Autowired RolRepository roles; @Autowired ServicioRepository servicios; @Autowired AtencionPeluqueriaRepository atenciones; @Autowired FotoPeluqueriaRepository fotos; @Autowired PagoRepository pagos; @Autowired DetallePagoRepository detalles; @Autowired ComprobanteRepository comprobantes;
 @MockitoBean ImageStorageService storage;
 @BeforeEach void clean(){comprobantes.deleteAll();detalles.deleteAll();pagos.deleteAll();fotos.deleteAll();atenciones.deleteAll();citaServicios.deleteAll();citas.deleteAll();mascotas.deleteAll();clientes.deleteAll();usuarioRoles.deleteAll();servicios.deleteAll();usuarios.deleteAll();}
 @Test void completesHairdressingPaymentAndReceiptFlow() throws Exception{Fixture f=fixture();when(storage.upload(org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString())).thenReturn(new StoredImage("https://fake/image.jpg","fake/public-id"));String attention=mvc.perform(post("/api/v1/citas/{id}/atencion-peluqueria",f.cita.getId()).with(token(f.worker,"PELUQUERO")).contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();long attentionId=Long.parseLong(attention.replaceAll(".*\\\"id\\\":(\\d+).*","$1"));assertThat(citas.findById(f.cita.getId()).orElseThrow().getEstado()).isEqualTo(EstadoCita.CONFIRMADA);MockMultipartFile image=new MockMultipartFile("archivo","before.jpg","image/jpeg",new byte[]{(byte)0xff,(byte)0xd8,(byte)0xff,0});mvc.perform(multipart("/api/v1/atenciones-peluqueria/{id}/evidencias",attentionId).file(image).param("tipoFoto","FINAL").with(token(f.worker,"PELUQUERO"))).andExpect(status().isCreated()).andExpect(jsonPath("$.urlArchivo").value("https://fake/image.jpg"));mvc.perform(patch("/api/v1/atenciones-peluqueria/{id}/cerrar",attentionId).with(token(f.worker,"PELUQUERO"))).andExpect(status().isOk());assertThat(citas.findById(f.cita.getId()).orElseThrow().getEstado()).isEqualTo(EstadoCita.ATENDIDA);mvc.perform(post("/api/v1/citas/{id}/pagos",f.cita.getId()).with(token(f.receptionist,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content("{\"detalles\":[{\"medioPago\":\"EFECTIVO\",\"monto\":30},{\"medioPago\":\"YAPE\",\"monto\":20}]}" )).andExpect(status().isOk()).andExpect(jsonPath("$.montoTotal").value(50.0));String paymentId=String.valueOf(pagos.findAll().get(0).getId());mvc.perform(post("/api/v1/pagos/{id}/comprobante",paymentId).with(token(f.receptionist,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content("{\"tipoComprobante\":\"BOLETA\",\"serie\":\"B001\",\"numero\":\"1\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.estado").value("EMITIDO")).andExpect(jsonPath("$.citaId").value(f.cita.getId()));}
 private Fixture fixture(){Usuario worker=user("flow-worker"+System.nanoTime()+"@t.dev",NombreRol.PELUQUERO);Usuario receptionist=user("flow-reception"+System.nanoTime()+"@t.dev",NombreRol.RECEPCIONISTA);Cliente c=new Cliente();c.setPrimerNombre("Cliente");c.setPrimerApellido("Flujo");c.setTipoDocumento(TipoDocumento.DNI);c.setNumeroDocumento(String.valueOf(90000000+(int)(Math.random()*999999)));c.setActivo(true);c=clientes.saveAndFlush(c);Mascota m=new Mascota();m.setCliente(c);m.setNombre("Milo");m.setEspecie(EspecieMascota.PERRO);m.setActivo(true);m=mascotas.saveAndFlush(m);Cita cita=new Cita();cita.setMascota(m);cita.setTrabajadorAsignado(worker);cita.setRegistradoPor(receptionist);cita.setTipoCita(TipoCita.PELUQUERIA);cita.setEstado(EstadoCita.CONFIRMADA);LocalDateTime t=LocalDateTime.now().minusMinutes(30).withSecond(0).withNano(0);cita.setFechaHoraInicio(t);cita.setFechaHoraFin(t.plusMinutes(45));cita=citas.saveAndFlush(cita);Servicio s=new Servicio();s.setNombre("ServicioFlujo"+System.nanoTime());s.setTipoServicio(TipoServicio.PELUQUERIA);s.setPrecioBase(new BigDecimal("50"));s.setDuracionMinutos(45);s.setActivo(true);s=servicios.saveAndFlush(s);CitaServicio cs=new CitaServicio();cs.setCita(cita);cs.setServicio(s);cs.setPrecioAplicado(new BigDecimal("50"));cs.setDuracionAplicadaMinutos(45);citaServicios.saveAndFlush(cs);return new Fixture(cita,worker,receptionist);}
 private Usuario user(String email,NombreRol role){Usuario u=new Usuario();u.setPrimerNombre("Test");u.setPrimerApellido("Flow");u.setCorreo(email);u.setPasswordHash("hash");u.setActivo(true);u.setIntentosFallidos(0);u=usuarios.saveAndFlush(u);UsuarioRol ur=new UsuarioRol();ur.setUsuario(u);ur.setRol(roles.findByNombre(role).orElseThrow());usuarioRoles.saveAndFlush(ur);return u;}private RequestPostProcessor token(Usuario u,String role){return jwt().jwt(j->j.claim("uid",u.getId().toString())).authorities(new SimpleGrantedAuthority("ROLE_"+role));}private record Fixture(Cita cita,Usuario worker,Usuario receptionist){}
 @Test void cannotSkipEvidenceOrPaymentStages() throws Exception{Fixture f=fixture();String attention=mvc.perform(post("/api/v1/citas/{id}/atencion-peluqueria",f.cita.getId()).with(token(f.worker,"PELUQUERO")).contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();long id=Long.parseLong(attention.replaceAll(".*\\\"id\\\":(\\d+).*","$1"));mvc.perform(patch("/api/v1/atenciones-peluqueria/{id}/cerrar",id).with(token(f.worker,"PELUQUERO"))).andExpect(status().isConflict());assertThat(citas.findById(f.cita.getId()).orElseThrow().getEstado()).isEqualTo(EstadoCita.CONFIRMADA);mvc.perform(post("/api/v1/citas/{id}/pagos",f.cita.getId()).with(token(f.receptionist,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content("{\"detalles\":[{\"medioPago\":\"EFECTIVO\",\"monto\":10}]}" )).andExpect(status().isConflict());}
}
