package com.veterinaria.backend.pago;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.math.BigDecimal; import java.time.LocalDateTime; import java.util.List;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.http.MediaType; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
import com.veterinaria.backend.cita.entity.*; import com.veterinaria.backend.cita.enums.*; import com.veterinaria.backend.cita.repository.*; import com.veterinaria.backend.cliente.entity.Cliente; import com.veterinaria.backend.cliente.enums.TipoDocumento; import com.veterinaria.backend.cliente.repository.ClienteRepository; import com.veterinaria.backend.mascota.entity.Mascota; import com.veterinaria.backend.mascota.enums.EspecieMascota; import com.veterinaria.backend.mascota.repository.MascotaRepository; import com.veterinaria.backend.pago.repository.*; import com.veterinaria.backend.servicio.entity.Servicio; import com.veterinaria.backend.servicio.enums.TipoServicio; import com.veterinaria.backend.servicio.repository.ServicioRepository; import com.veterinaria.backend.support.PostgreSqlContainerConfiguration; import com.veterinaria.backend.usuario.entity.*; import com.veterinaria.backend.usuario.enums.NombreRol; import com.veterinaria.backend.usuario.repository.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") @Transactional
class PagoIntegrationTest extends PostgreSqlContainerConfiguration {
 @Autowired MockMvc mvc; @Autowired PagoRepository pagos; @Autowired DetallePagoRepository detalles; @Autowired CitaRepository citas; @Autowired CitaServicioRepository citaServicios; @Autowired ClienteRepository clientes; @Autowired MascotaRepository mascotas; @Autowired UsuarioRepository usuarios; @Autowired UsuarioRolRepository usuarioRoles; @Autowired RolRepository roles; @Autowired ServicioRepository servicios;
 @BeforeEach void clean(){detalles.deleteAll();pagos.deleteAll();citaServicios.deleteAll();citas.deleteAll();mascotas.deleteAll();clientes.deleteAll();usuarioRoles.deleteAll();servicios.deleteAll();usuarios.deleteAll();}
 @Test void requiresAuthentication() throws Exception{Fixture f=fixture(EstadoCita.ATENDIDA,100);mvc.perform(post("/api/v1/citas/{id}/pagos",f.cita.getId()).contentType(MediaType.APPLICATION_JSON).content(payment("40"))).andExpect(status().isUnauthorized());}
 @Test void receptionistRegistersPartialMixedPaymentAndGetsIt() throws Exception{Fixture f=fixture(EstadoCita.ATENDIDA,100);mvc.perform(post("/api/v1/citas/{id}/pagos",f.cita.getId()).with(token(f.receptionist,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content(mixed())).andExpect(status().isOk()).andExpect(jsonPath("$.montoTotal").value(50.0)).andExpect(jsonPath("$.estado").value("PAGADO")).andExpect(jsonPath("$.detalles.length()").value(2));mvc.perform(get("/api/v1/citas/{id}/pagos",f.cita.getId()).with(token(f.receptionist,"RECEPCIONISTA"))).andExpect(status().isOk()).andExpect(jsonPath("$.content.length()").value(1));}
 @Test void allNonCashMeansAreAccepted() throws Exception{Fixture f=fixture(EstadoCita.ATENDIDA,100);for(String medio:List.of("PLIN","TARJETA")){mvc.perform(post("/api/v1/citas/{id}/pagos",f.cita.getId()).with(token(f.receptionist,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content("{\"detalles\":[{\"medioPago\":\""+medio+"\",\"monto\":10}]}" )).andExpect(status().isOk());}assertThat(pagos.sumPagadoByCitaId(f.cita.getId())).isEqualByComparingTo("20");}
 @Test void rejectsForbiddenRolesAndInvalidStates() throws Exception{Fixture f=fixture(EstadoCita.ATENDIDA,100);mvc.perform(post("/api/v1/citas/{id}/pagos",f.cita.getId()).with(token(f.worker,"VETERINARIO")).contentType(MediaType.APPLICATION_JSON).content(payment("10"))).andExpect(status().isForbidden());for(EstadoCita state:List.of(EstadoCita.PENDIENTE,EstadoCita.CONFIRMADA,EstadoCita.CANCELADA,EstadoCita.NO_ATENDIDA)){Fixture x=fixture(state,100);mvc.perform(post("/api/v1/citas/{id}/pagos",x.cita.getId()).with(token(x.receptionist,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content(payment("10"))).andExpect(status().isConflict());}}
 @Test void secondPaymentConsumesRemainingBalanceAndOverpayFails() throws Exception{Fixture f=fixture(EstadoCita.ATENDIDA,100);pay(f,60);pay(f,40);mvc.perform(post("/api/v1/citas/{id}/pagos",f.cita.getId()).with(token(f.receptionist,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content(payment("1"))).andExpect(status().isConflict());assertThat(pagos.sumPagadoByCitaId(f.cita.getId())).isEqualByComparingTo("100");}
 @Test void nonexistentAppointmentReturnsNotFound() throws Exception{Usuario u=user("missing"+System.nanoTime()+"@t.dev",NombreRol.RECEPCIONISTA);mvc.perform(post("/api/v1/citas/999999/pagos").with(token(u,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content(payment("1"))).andExpect(status().isNotFound());}
 private void pay(Fixture f,int n)throws Exception{mvc.perform(post("/api/v1/citas/{id}/pagos",f.cita.getId()).with(token(f.receptionist,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content(payment(String.valueOf(n)))).andExpect(status().isOk());} private String payment(String n){return "{\"detalles\":[{\"medioPago\":\"EFECTIVO\",\"monto\":"+n+",\"referencia\":\"  \"}]}";} private String mixed(){return "{\"detalles\":[{\"medioPago\":\"EFECTIVO\",\"monto\":30},{\"medioPago\":\"YAPE\",\"monto\":20}]}";}
 private Fixture fixture(EstadoCita state,int price){Usuario worker=user("worker"+System.nanoTime()+"@t.dev",NombreRol.PELUQUERO);Usuario receptionist=user("reception"+System.nanoTime()+"@t.dev",NombreRol.RECEPCIONISTA);Cliente c=new Cliente();c.setPrimerNombre("Cliente");c.setPrimerApellido("Pago");c.setTipoDocumento(TipoDocumento.DNI);c.setNumeroDocumento(String.valueOf(70000000+(int)(Math.random()*999999)));c.setActivo(true);c=clientes.saveAndFlush(c);Mascota m=new Mascota();m.setCliente(c);m.setNombre("Luna");m.setEspecie(EspecieMascota.PERRO);m.setActivo(true);m=mascotas.saveAndFlush(m);Cita cita=new Cita();cita.setMascota(m);cita.setTrabajadorAsignado(worker);cita.setRegistradoPor(receptionist);cita.setTipoCita(TipoCita.PELUQUERIA);cita.setEstado(state);cita.setMotivoCancelacion("fixture");cita.setMotivoNoAtencion("fixture");LocalDateTime start=LocalDateTime.now().minusHours(1).withSecond(0).withNano(0);cita.setFechaHoraInicio(start);cita.setFechaHoraFin(start.plusMinutes(45));cita=citas.saveAndFlush(cita);Servicio s=new Servicio();s.setNombre("Corte"+System.nanoTime());s.setTipoServicio(TipoServicio.PELUQUERIA);s.setPrecioBase(BigDecimal.valueOf(price));s.setDuracionMinutos(45);s.setActivo(true);s=servicios.saveAndFlush(s);CitaServicio cs=new CitaServicio();cs.setCita(cita);cs.setServicio(s);cs.setPrecioAplicado(BigDecimal.valueOf(price));cs.setDuracionAplicadaMinutos(45);citaServicios.saveAndFlush(cs);return new Fixture(cita,worker,receptionist);}
 private Usuario user(String email,NombreRol role){Usuario u=new Usuario();u.setPrimerNombre("Test");u.setPrimerApellido("User");u.setCorreo(email);u.setPasswordHash("hash");u.setActivo(true);u.setIntentosFallidos(0);u=usuarios.saveAndFlush(u);UsuarioRol ur=new UsuarioRol();ur.setUsuario(u);ur.setRol(roles.findByNombre(role).orElseThrow());usuarioRoles.saveAndFlush(ur);return u;} private org.springframework.test.web.servlet.request.RequestPostProcessor token(Usuario u,String role){return jwt().jwt(j->j.claim("uid",u.getId().toString())).authorities(new SimpleGrantedAuthority("ROLE_"+role));} private record Fixture(Cita cita,Usuario worker,Usuario receptionist){}
}
