package com.veterinaria.backend.comprobante;

import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.math.BigDecimal; import java.time.LocalDateTime;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.http.MediaType; import org.springframework.security.core.authority.SimpleGrantedAuthority; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
import com.veterinaria.backend.cita.entity.Cita; import com.veterinaria.backend.cita.enums.*; import com.veterinaria.backend.cita.repository.CitaRepository; import com.veterinaria.backend.cliente.entity.Cliente; import com.veterinaria.backend.cliente.enums.TipoDocumento; import com.veterinaria.backend.cliente.repository.ClienteRepository; import com.veterinaria.backend.mascota.entity.Mascota; import com.veterinaria.backend.mascota.enums.EspecieMascota; import com.veterinaria.backend.mascota.repository.MascotaRepository; import com.veterinaria.backend.pago.entity.Pago; import com.veterinaria.backend.pago.enums.EstadoPago; import com.veterinaria.backend.pago.repository.PagoRepository; import com.veterinaria.backend.support.PostgreSqlContainerConfiguration; import com.veterinaria.backend.usuario.entity.*; import com.veterinaria.backend.usuario.enums.NombreRol; import com.veterinaria.backend.usuario.repository.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") @Transactional
class ComprobanteIntegrationTest extends PostgreSqlContainerConfiguration {
 @Autowired MockMvc mvc; @Autowired PagoRepository pagos; @Autowired CitaRepository citas; @Autowired MascotaRepository mascotas; @Autowired ClienteRepository clientes; @Autowired UsuarioRepository usuarios; @Autowired UsuarioRolRepository usuarioRoles; @Autowired RolRepository roles;
 @BeforeEach void clean(){pagos.deleteAll();citas.deleteAll();mascotas.deleteAll();clientes.deleteAll();usuarioRoles.deleteAll();usuarios.deleteAll();}
 @Test void paidPaymentEmitsAndCanBeRead() throws Exception{Fixture f=fixture(EstadoPago.PAGADO,NombreRol.RECEPCIONISTA);String json="{\"tipoComprobante\":\"BOLETA\",\"serie\":\" B001 \",\"numero\":\" 7 \"}";String response=mvc.perform(post("/api/v1/pagos/{id}/comprobante",f.pago.getId()).with(token(f.user,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content(json)).andExpect(status().isOk()).andExpect(jsonPath("$.estado").value("EMITIDO")).andExpect(jsonPath("$.serie").value("B001")).andExpect(jsonPath("$.numero").value("7")).andReturn().getResponse().getContentAsString();long id=Long.parseLong(response.replaceAll(".*\\\"id\\\":(\\d+).*","$1"));mvc.perform(get("/api/v1/comprobantes/{id}",id).with(token(f.user,"RECEPCIONISTA"))).andExpect(status().isOk()).andExpect(jsonPath("$.pagoId").value(f.pago.getId()));}
 @Test void invoiceRequiresFiscalFieldsAndUnpaidIsRejected() throws Exception{Fixture f=fixture(EstadoPago.PAGADO,NombreRol.ADMINISTRADOR);mvc.perform(post("/api/v1/pagos/{id}/comprobante",f.pago.getId()).with(token(f.user,"ADMINISTRADOR")).contentType(MediaType.APPLICATION_JSON).content("{\"tipoComprobante\":\"FACTURA\",\"serie\":\"F001\",\"numero\":\"1\",\"ruc\":\"123\"}")).andExpect(status().isBadRequest());Fixture unpaid=fixture(EstadoPago.PENDIENTE,NombreRol.ADMINISTRADOR);mvc.perform(post("/api/v1/pagos/{id}/comprobante",unpaid.pago.getId()).with(token(unpaid.user,"ADMINISTRADOR")).contentType(MediaType.APPLICATION_JSON).content("{\"tipoComprobante\":\"BOLETA\",\"serie\":\"B001\",\"numero\":\"2\"}")).andExpect(status().isConflict());}
 @Test void duplicatePaymentComprobanteIsConflictAndForbiddenRoleIs403() throws Exception{Fixture f=fixture(EstadoPago.PAGADO,NombreRol.RECEPCIONISTA);String json="{\"tipoComprobante\":\"BOLETA\",\"serie\":\"B001\",\"numero\":\"1\"}";mvc.perform(post("/api/v1/pagos/{id}/comprobante",f.pago.getId()).with(token(f.user,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content(json)).andExpect(status().isOk());mvc.perform(post("/api/v1/pagos/{id}/comprobante",f.pago.getId()).with(token(f.user,"RECEPCIONISTA")).contentType(MediaType.APPLICATION_JSON).content(json)).andExpect(status().isConflict());mvc.perform(get("/api/v1/pagos/{id}/comprobante",f.pago.getId()).with(token(f.user,"VETERINARIO"))).andExpect(status().isForbidden());}
 @Test void noTokenAndMissingPayment() throws Exception{mvc.perform(get("/api/v1/pagos/999999/comprobante")).andExpect(status().isUnauthorized());}
 private Fixture fixture(EstadoPago state,NombreRol role){Usuario u=user("bill"+System.nanoTime()+"@t.dev",role);Cliente c=new Cliente();c.setPrimerNombre("Cliente");c.setPrimerApellido("Factura");c.setTipoDocumento(TipoDocumento.DNI);c.setNumeroDocumento(String.valueOf(80000000+(int)(Math.random()*999999)));c.setActivo(true);c=clientes.saveAndFlush(c);Mascota m=new Mascota();m.setCliente(c);m.setNombre("Nina");m.setEspecie(EspecieMascota.PERRO);m.setActivo(true);m=mascotas.saveAndFlush(m);Cita cita=new Cita();cita.setMascota(m);cita.setTrabajadorAsignado(u);cita.setRegistradoPor(u);cita.setTipoCita(TipoCita.PELUQUERIA);cita.setEstado(EstadoCita.ATENDIDA);LocalDateTime t=LocalDateTime.now().minusHours(1).withSecond(0).withNano(0);cita.setFechaHoraInicio(t);cita.setFechaHoraFin(t.plusMinutes(30));cita=citas.saveAndFlush(cita);Pago p=new Pago();p.setCita(cita);p.setRegistradoPor(u);p.setMontoTotal(new BigDecimal("20"));p.setEstado(state);p.setFechaPago(state==EstadoPago.PAGADO?t:null);p=pagos.saveAndFlush(p);return new Fixture(p,u);}
 private Usuario user(String email,NombreRol role){Usuario u=new Usuario();u.setPrimerNombre("Test");u.setPrimerApellido("User");u.setCorreo(email);u.setPasswordHash("hash");u.setActivo(true);u.setIntentosFallidos(0);u=usuarios.saveAndFlush(u);UsuarioRol ur=new UsuarioRol();ur.setUsuario(u);ur.setRol(roles.findByNombre(role).orElseThrow());usuarioRoles.saveAndFlush(ur);return u;} private org.springframework.test.web.servlet.request.RequestPostProcessor token(Usuario u,String role){return jwt().jwt(j->j.claim("uid",u.getId().toString())).authorities(new SimpleGrantedAuthority("ROLE_"+role));} private record Fixture(Pago pago,Usuario user){}
}
